title: Queenstown Community
url: https://www.queenstown.pa.gov.sg
favicon: /images/favicon.png
colors:
  primary-color: "#356aff"
  secondary-color: "#102a80"
  media-colors:
    - title: media-color-one
      color: "#102a80"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2k14e3dkp8goc.amplifyapp.com
prod: https://master.d2k14e3dkp8goc.amplifyapp.com
facebook-pixel: "1677423322755264"
resources_name: test
shareicon: /images/shareicon.png
is_government: false
google_analytics_ga4: G-TCGSHDX9WT
linkedin-insights: ""
